use std::fmt::Write as _;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-env-changed=SDL3_DIR");
    println!("cargo:rerun-if-changed=../vendor/sdl3");

    // Prefer an explicit SDL3_DIR, then the workspace vendor directory
    // (<workspace>/vendor/sdl3, one level above this crate). When neither
    // exists, sdl3-sys falls back to the system SDL3.
    let dir = std::env::var_os("SDL3_DIR")
        .map(PathBuf::from)
        .filter(|p| p.join("lib").is_dir())
        .or_else(|| {
            let vendor = PathBuf::from("../vendor/sdl3");
            vendor.join("lib").is_dir().then_some(vendor)
        });

    if let Some(dir) = dir {
        // Absolute paths keep the link search and rpath valid no matter where
        // the binary is run from.
        let dir = std::fs::canonicalize(&dir).unwrap_or(dir);
        let lib = dir.join("lib");
        println!("cargo:rustc-link-search=native={}", lib.display());
        println!("cargo:rustc-link-lib=dylib=SDL3");
        if std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("linux") {
            println!("cargo:rustc-link-arg=-Wl,-rpath,{}", lib.display());
        }
    }

    emit_enemy_scripts();
}

/// Generate the pack-entry table for the checked-in enemy scripts under
/// `games/re1/enemy/`, so `convert-game` packs exactly the scripts in the tree
/// without a hand-maintained list.
fn emit_enemy_scripts() {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("games/re1/enemy");
    println!("cargo:rerun-if-changed=games/re1/enemy");

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    collect_lua(&root, "enemy", &mut entries);
    entries.sort_by_key(|(entry, _)| entry.to_ascii_lowercase());

    let mut out = String::from(
        "// @generated by build.rs from games/re1/enemy: the pack entries for\n\
         // the checked-in enemy scripts.\n\
         pub static ENEMY_SCRIPTS: &[(&str, &str)] = &[\n",
    );
    for (entry, path) in &entries {
        writeln!(
            out,
            "    ({entry:?}, include_str!({:?})),",
            path.to_string_lossy()
        )
        .expect("writing to a String cannot fail");
    }
    out.push_str("];\n");

    let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").expect("cargo sets OUT_DIR"));
    std::fs::write(out_dir.join("enemy_scripts.rs"), out)
        .expect("failed to write the generated enemy-script table");
}

/// Recursively collect every `.lua` file under `dir`, naming each pack entry
/// with the `prefix` path in `/` separators.
fn collect_lua(dir: &PathBuf, prefix: &str, entries: &mut Vec<(String, PathBuf)>) {
    let Ok(read) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in read.flatten() {
        let path = entry.path();
        let name = entry.file_name();
        let name = name.to_string_lossy();
        if name.starts_with('.') {
            continue;
        }
        if path.is_dir() {
            collect_lua(&path, &format!("{prefix}/{name}"), entries);
        } else if name.to_ascii_lowercase().ends_with(".lua") {
            entries.push((format!("{prefix}/{name}"), path));
        }
    }
}
