//! Shared `cargo-fuzz` entry points for every arklay parser.
//!
//! Each function is exactly the public entry point the engine uses, with the
//! same budgets in effect. Seeds under `fuzz/seeds/<target>/` are generated by
//! `cargo test --test torture -- --ignored write_fuzz_seeds`; they are
//! synthetic and contain no game data.

use arklay::avi::Avi;
use arklay::cinepak::Decoder;
use arklay::game::GameState;
use arklay::lua::LuaVm;
use arklay::manifest::Manifest;
use arklay::pack::{Pack, PackWriter};
use arklay::save::SaveFile;
use arklay::state::RoomId;
use arklay::{audio, bmp, emd, ivm, lzw, mask, rdt, scd, tim, tmd};

pub fn pack(data: &[u8]) {
    let _ = Pack::from_bytes(data.to_vec());
}

pub fn manifest(data: &[u8]) {
    let _ = Manifest::parse(&String::from_utf8_lossy(data));
}

pub fn rdt(data: &[u8]) {
    let _ = rdt::parse(data, RoomId::parse("1000").unwrap());
}

pub fn scd(data: &[u8]) {
    let _ = scd::reader::parse(data);
}

pub fn scd_asm(data: &[u8]) {
    let text = String::from_utf8_lossy(data);
    if let Ok(assembled) = scd::asm::assemble(&text) {
        let _ = assembled.to_container();
    }
}

pub fn emd(data: &[u8]) {
    let _ = emd::parse(data);
    let _ = emd::parse_emw(data);
}

pub fn tim(data: &[u8]) {
    let _ = tim::decode(data);
    let _ = tim::decode_8bpp(data);
    let _ = tim::decode_4bpp(data);
}

pub fn tmd(data: &[u8]) {
    let _ = tmd::parse(data);
}

pub fn ivm(data: &[u8]) {
    let _ = ivm::parse(data);
}

pub fn avi(data: &[u8]) {
    let _ = Avi::parse(data.to_vec());
}

pub fn cinepak(data: &[u8]) {
    // Decode twice so the codebook and canvas carry state across frames.
    if let Ok(mut decoder) = Decoder::new(320, 240) {
        let _ = decoder.decode(data);
        let _ = decoder.decode(data);
    }
}

pub fn lzw(data: &[u8]) {
    let _ = lzw::decode(data);
}

pub fn bmp(data: &[u8]) {
    let _ = bmp::decode(data);
    let _ = bmp::decode_mask(data);
}

pub fn save(data: &[u8]) {
    let _ = SaveFile::from_bytes(data);
}

pub fn mask(data: &[u8]) {
    let _ = mask::MaskTable::parse(data, 4);
}

pub fn wav(data: &[u8]) {
    let _ = audio::parse_wav(data);
}

/// Build a one-entry v1 pack with `lua/fuzz.lua` holding the input, then load
/// and run the sandboxed hooks so the memory and instruction budgets are
/// exercised rather than bare `mlua`.
pub fn lua(data: &[u8]) {
    let mut writer = PackWriter::new();
    if writer.add("lua/fuzz.lua", data.to_vec()).is_err() {
        return;
    }
    let Ok(bytes) = writer.to_bytes() else {
        return;
    };
    let Ok(pack) = Pack::from_bytes(bytes) else {
        return;
    };
    let Ok(Some(vm)) = LuaVm::load(&pack) else {
        return;
    };
    let mut game = GameState::default();
    let id = game.id;
    vm.call_room_load(&mut game, id);
    vm.call_tick(&mut game, 1);
    let _ = vm.filter_message(&mut game, 1);
}
