//! Scripted-character (NPC) driver and model metadata.
//!
//! Entity ids `0x20..=0x2E` are the game's human characters. [`data`] holds
//! their model paths, collision radii, per-character init data and behaviour
//! dispatch tables, [`idle`] their state-1 behaviours plus the state-0 spawn
//! init, and [`anim`] the per-entity animation clock that publishes the pending
//! frame into the entity words the scripts and behaviours read. [`update_all`]
//! runs the driver for every active entity slot and is called by the room tick
//! after the event VM.
//!
//! # Documented deviations from the original
//!
//! - **Monsters run pack scripts.** Entity ids `0x00..=0x1F` allocate and
//!   dispatch to the pack's `enemy/em{id:02x}.lua` script; an id whose script
//!   (or model) the pack does not carry parks inert. Monster behaviour that
//!   has not been ported yet therefore stays empty until its script lands.
//! - **Weapon-joint spawns use the entity matrix.** Handler 08's muzzle and
//!   secondary flash live in the weapon hand's joint space in the original
//!   (`joints + 0x70C`); the port has no game-layer joint matrices, so it
//!   attaches them to the character's entity matrix with the original
//!   per-frame offsets. The death blood sheets use the same approximation, so
//!   the paint pivots around the body instead of the exact hand/wound.
//! - **Flamethrower cues are timing-only.** The two looping enemy-bank 3D cues
//!   (ids `0x1E`/`0x1F`) have no packed WAV, so handler 08 reproduces their
//!   countdown loop but queues no audio.
//! - **No combat.** Behaviours 10, 37, 43 and 45 stay counted placeholders and
//!   no shipped script or effect animation reaches them; the corpus audit locks
//!   that. There is no damage, health or hit reaction.
//! - **The shadow quad is not adjustable at runtime.** NPC ground shadows are
//!   drawn from [`data::character_shadow`], including the wounded-Rebecca and
//!   variant-Wesker tint/resize overrides, but the original's per-entity quad
//!   at `entity+0xE4` is not modelled, so the scripted deaths' growing ground
//!   billboard stays deferred.
//! - **Joint tints and hiding are not applied.** The wounded Rebecca joint
//!   tints, the joint flag bit her init clears, Wesker's zeroed tracking-joint
//!   yaw/pitch and 0x10 pitch step, and the `model_op`/`objs_hide` joint
//!   colour/visibility writes have no renderer support yet.
//! - **Look-at is simplified.** The original slews a tracking joint every
//!   update; this port stores the target and steps the entity yaw in the walk
//!   layer.
//! - **Pathfinding starts from fresh scratch.** [`walk::zone_path_find`] ports
//!   the original's distance-weighted CW/CCW ring walk over the zone graph,
//!   including the `to.z == 0` zone-index entry, but seeds each walk's scratch
//!   arrays to zero instead of reusing the original's stale globals, so the
//!   same inputs always take the same route.
//! - **RNG is deterministic.** The look-at scheduling reads the platform
//!   stream's per-frame draw (`GameState::rand_seed`); only the consumer call
//!   order within a frame is the port's own.

use std::collections::{HashMap, HashSet};
use std::sync::Arc;

use crate::emd;
use crate::game::{ENTITY_COUNT, ENTITY_STATUS_ACTIVE, GameState};
use crate::model::{Clip, Emd, Keyframe};
use crate::pack::Pack;
use crate::state::RoomState;

pub mod anim;
pub mod companion;
pub mod custom_anim;
pub mod data;
pub mod idle;
pub mod lua;
pub mod scd;
pub mod tyrant;
pub mod walk;
pub mod web;
pub mod yawn;

pub use anim::EntityAnim;
pub use data::{
    CharacterInit, FIRST_ID, LAST_ID, RADIUS_LARGE, RADIUS_MEDIUM, RADIUS_SPRAWLED, character_init,
    character_name, character_shadow, collision_radius, model_path, shadow_tint,
};
pub use lua::LuaEnemyHost;

mod scripts {
    include!(concat!(env!("OUT_DIR"), "/enemy_scripts.rs"));
}
/// The checked-in enemy scripts as `(pack entry, source)` pairs, generated by
/// `build.rs`; the converter packs exactly this set.
pub use scripts::ENEMY_SCRIPTS;

/// First entity id backed by an `enemy/*.emd` model.
pub const CHARACTER_ID_MIN: u8 = data::FIRST_ID;
/// Last entity id backed by an `enemy/*.emd` model.
pub const CHARACTER_ID_MAX: u8 = data::LAST_ID;

/// Y offset the look-at target is aimed at on an entity target, below its
/// origin: the original shifts the target's Y by `-0xA28` (head height).
const LOOK_AT_HEAD_HEIGHT: i32 = 0xA28;

/// Clip blend step the state-0 init and the state-1 idle behaviours pass to
/// the animation clock (the `0x400` the original's handlers use).
const IDLE_BLEND_STEP: u16 = 0x400;

/// Parsed entity models, keyed by `(id, player index)`.
///
/// The cache loads the entity's pack entry on first use and keeps the parsed
/// model for the rest of the session, so every entity with the same id and
/// scenario shares one copy. Scripted characters (`0x20..=0x2E`) have a single
/// model; monsters (`0x00..=0x15`) prefer the scenario block
/// `enemy/em{id:02x}{player}.emd` and fall back to the generic
/// `enemy/em{id:02x}.emd` when the pack carries no scenario-specific entry.
/// A missing or invalid entry is logged once and remembered as absent: the
/// entity still exists and its script still runs, it just has no clips to
/// animate with and no mesh to draw.
#[derive(Default)]
pub struct EntityModelCache {
    pub(crate) models: HashMap<(u8, u8), Arc<Emd>>,
    pub(crate) missing: HashSet<(u8, u8)>,
    /// Keyframe-only views of the loaded models, so every entity's animation
    /// clock can share one table without cloning it each tick.
    pub(crate) keyframe_sets: HashMap<(u8, u8), Arc<Vec<Keyframe>>>,
    /// Skeleton-only views of the loaded models, shared with the animation
    /// clocks that compose joint world matrices.
    pub(crate) skeleton_sets: HashMap<(u8, u8), Arc<crate::model::Skeleton>>,
    /// The character held-weapon meshes (`player/ws*.tmd`), keyed by file id.
    pub(crate) weapon_tmds: HashMap<u16, Arc<crate::model::Tmd>>,
    /// Held-weapon file ids the pack does not carry.
    pub(crate) weapon_missing: HashSet<u16>,
}

/// The pack entry candidates for entity `id` in the given scenario, in
/// preference order. Characters have one model; monsters fall back from the
/// scenario block to the generic entry.
fn model_candidates(id: u8, player: u8) -> Vec<String> {
    if (data::FIRST_ID..=data::LAST_ID).contains(&id) {
        return data::model_path(id)
            .map(str::to_owned)
            .into_iter()
            .collect();
    }
    if id < CHARACTER_ID_MIN {
        return vec![
            format!("enemy/em{id:02x}{player}.emd"),
            format!("enemy/em{id:02x}.emd"),
        ];
    }
    Vec::new()
}

impl EntityModelCache {
    /// The keyframe table of entity `(id, player)`, built once per loaded
    /// model and shared with the animation clocks.
    pub fn keyframes(&mut self, pack: &Pack, id: u8, player: u8) -> Option<Arc<Vec<Keyframe>>> {
        let key = (id, player & 1);
        if let Some(set) = self.keyframe_sets.get(&key) {
            return Some(Arc::clone(set));
        }
        let model = self.get(pack, id, player)?;
        let set = Arc::new(model.keyframes.clone());
        self.keyframe_sets.insert(key, Arc::clone(&set));
        Some(set)
    }

    /// The joint hierarchy of entity `(id, player)`, built once per loaded
    /// model and shared with the animation clocks.
    pub fn skeleton(
        &mut self,
        pack: &Pack,
        id: u8,
        player: u8,
    ) -> Option<Arc<crate::model::Skeleton>> {
        let key = (id, player & 1);
        if let Some(set) = self.skeleton_sets.get(&key) {
            return Some(Arc::clone(set));
        }
        let model = self.get(pack, id, player)?;
        let set = Arc::new(model.skeleton.clone());
        self.skeleton_sets.insert(key, Arc::clone(&set));
        Some(set)
    }

    /// The parsed model for entity `(id, player)`, loading it from the pack on
    /// first use. Ids outside the dispatchable range yield `None` without a
    /// warning.
    pub fn get(&mut self, pack: &Pack, id: u8, player: u8) -> Option<Arc<Emd>> {
        let key = (id, player & 1);
        if let Some(model) = self.models.get(&key) {
            return Some(Arc::clone(model));
        }
        if self.missing.contains(&key) {
            return None;
        }
        let candidates = model_candidates(id, key.1);
        if candidates.is_empty() {
            self.missing.insert(key);
            return None;
        }
        for path in &candidates {
            let bytes = match pack.read(path) {
                Ok(bytes) => bytes,
                Err(_) => continue,
            };
            match emd::parse(bytes) {
                Ok(model) => {
                    let model = Arc::new(model);
                    self.models.insert(key, Arc::clone(&model));
                    return Some(model);
                }
                Err(err) => {
                    eprintln!("warning: invalid enemy model {path}: {err:#}");
                }
            }
        }
        eprintln!("warning: no model available for entity {id:#04x} (tried {candidates:?})");
        self.missing.insert(key);
        None
    }

    /// The parsed character held-weapon mesh for a `WS*.TMD` file id, loading
    /// `player/ws{id:03x}.tmd` from the pack on first use.
    pub fn weapon_tmd(&mut self, pack: &Pack, id: u16) -> Option<Arc<crate::model::Tmd>> {
        if let Some(tmd) = self.weapon_tmds.get(&id) {
            return Some(Arc::clone(tmd));
        }
        if self.weapon_missing.contains(&id) {
            return None;
        }
        let path = format!("player/ws{id:03x}.tmd");
        match pack.read(&path).and_then(crate::tmd::parse) {
            Ok(tmd) => {
                let tmd = Arc::new(tmd);
                self.weapon_tmds.insert(id, Arc::clone(&tmd));
                Some(tmd)
            }
            Err(err) => {
                eprintln!("warning: missing held-weapon mesh {path}: {err:#}");
                self.weapon_missing.insert(id);
                None
            }
        }
    }
}

/// Repoint the player's damage scratch pair at a freshly loaded enemy model,
/// the original's `LoadEntityEMD` store at `EntityModelLoader.cpp:555-558`.
/// The last model with a second bank wins; a model without one leaves the
/// pair untouched, exactly like the original's `if (*puVar2 != 0)` guard.
pub(crate) fn note_player_damage_bank(
    game: &mut GameState,
    model: Option<&Emd>,
    keyframes: Option<Arc<Vec<Keyframe>>>,
) {
    let Some(model) = model else {
        return;
    };
    let Some(keyframes) = keyframes else {
        return;
    };
    if model.damage_clips.is_empty() {
        return;
    }
    game.player_damage = Some(Arc::new(crate::game::PlayerDamageBank {
        keyframes,
        clips: Arc::new(model.damage_clips.clone()),
    }));
}

/// One native update per active entity slot, called after the event VM and
/// before the player's physics mirror. Returns the number of slots updated.
///
/// Ids below `CHARACTER_ID_MIN` are monsters: their per-frame logic is the
/// pack's `enemy/em{id:02x}.lua` script, run through `lua`, and the script
/// owns its own message gate (the original gates most monsters on
/// `g_message_flags & 4`, the spider web on nothing) and its own tail. Ids at
/// or above `CHARACTER_ID_MIN` keep the native character driver; a displayed
/// message that masks the character-think bit pauses them, exactly as before.
pub fn update_all(
    game: &mut GameState,
    room: &RoomState,
    models: &mut EntityModelCache,
    pack: &Pack,
    mut lua: Option<&mut LuaEnemyHost>,
) -> usize {
    let player = game.id.player_flag & 1;
    let characters_frozen = game.message_freezes_entities();
    let mut updated = 0;
    for slot in 1..ENTITY_COUNT {
        if !game.entities[slot].active() {
            continue;
        }
        let id = game.entities[slot].id;
        if id < CHARACTER_ID_MIN {
            let model = models.get(pack, id, player);
            if let Some(keyframes) = models.keyframes(pack, id, player) {
                game.entity_anims[slot].keyframes = Some(Arc::clone(&keyframes));
                note_player_damage_bank(game, model.as_deref(), Some(keyframes));
            }
            if let Some(skeleton) = models.skeleton(pack, id, player) {
                game.entity_anims[slot].skeleton = Some(skeleton);
            }
            let clips: &[Clip] = model.as_ref().map_or(&[], |model| &model.clips);
            if let Some(host) = lua.as_deref_mut()
                && host.update(game, room, pack, slot, clips)
            {
                updated += 1;
            }
            continue;
        }
        if characters_frozen {
            continue;
        }
        let model = models.get(pack, id, player);
        if let Some(keyframes) = models.keyframes(pack, id, player) {
            game.entity_anims[slot].keyframes = Some(keyframes);
        }
        let clips: &[Clip] = model.as_ref().map_or(&[], |model| &model.clips);
        // The ported states of the character driver run from the pack's
        // script when one exists (states 0, 1, 8 and 9); the native driver
        // stays the fallback and the differential oracle.
        let scripted = matches!(game.entities[slot].state(), 0 | 1 | 8 | 9)
            && lua
                .as_deref_mut()
                .is_some_and(|host| host.update(game, room, pack, slot, clips));
        if !scripted {
            let target = live_look_at_target(game, slot);
            update_entity(game, slot, room, clips, target);
        }
        updated += 1;
    }
    updated
}

/// One entity's driver tick: the state dispatch plus the shared tail.
///
/// State 0 is the spawn init, state 1 the idle behaviours, state 8 the
/// scripted-action handlers and state 9 the follow/pathfind driver. `clips`
/// are the entity's EMD animation clips and `look_at_target` the live position
/// an entity-target `act_motion` is aiming at, when one is set.
pub fn update_entity(
    game: &mut GameState,
    slot: usize,
    room: &RoomState,
    clips: &[Clip],
    look_at_target: Option<[i32; 3]>,
) {
    let advance = match game.entities[slot].state() {
        0 => {
            idle::init(
                &mut game.entities[slot],
                &mut game.entity_anims[slot],
                clips,
                &game.flags,
                game.id,
            );
            false
        }
        1 => {
            // The bleeding-out death copies `g_EnemiesList[1]`'s facing, the
            // second enemy-list slot (the port's entity slot 2).
            let enemy_angle = game.entities.get(2).map_or(0, |entity| entity.angle);
            let (advance, spawns) = idle::update(
                &mut game.entities[slot],
                &mut game.entity_anims[slot],
                clips,
                room,
                enemy_angle,
            );
            idle::apply_spawns(game, slot, spawns);
            advance
        }
        8 => {
            scd::update(game, slot, room, clips);
            false
        }
        9 => {
            walk::update(game, slot, room, clips);
            false
        }
        _ => false,
    };
    if advance {
        game.entity_anims[slot].advance(&mut game.entities[slot], clips, false, IDLE_BLEND_STEP);
    }

    // Common tail: refresh the live look-at target, slew the tracking joint
    // toward it at the instruction's yaw/pitch step, and recompute the
    // camera-switch-zone shadow bit. The SCA hit-volume reset the original
    // shares this tail with stays with the enemy milestone.
    if let Some(target) = look_at_target {
        game.entities[slot].target = target;
    }
    game.entity_anims[slot].slew_look_at(&game.entities[slot]);
    game.entities[slot].has_enter_switch_zone = u8::from(in_camera_zone(
        room,
        room.current_cut,
        game.entities[slot].pos,
    ));
    game.entities[slot].status_flags |= ENTITY_STATUS_ACTIVE;
}

/// Whether `pos` lies inside the current camera's switch zone.
///
/// This is the room's zone test the player's ground shadow already uses: the
/// first zone whose `cam_from` names `camera` is that camera's header quad.
/// The original's character driver stores the result in the entity's
/// `has_enter_switch_zone` shadow bit every frame; the renderer then uses that
/// bit as a whole-entity gate, hiding every non-member joint (and off-zone
/// member joints) of a character that has not entered the zone.
pub fn in_camera_zone(room: &RoomState, camera: usize, pos: [i32; 3]) -> bool {
    room.zones
        .iter()
        .find(|zone| zone.cam_from >= 0 && zone.cam_from as usize == camera)
        .is_some_and(|zone| zone.contains(pos[0], pos[2]))
}

/// The look-at target to refresh this tick, or `None` when the entity's
/// look-at is not tracking a live entity. Bit `0x80` of `look_at_flags` asks
/// for the reload; the target's Y is biased down to head height.
pub(crate) fn live_look_at_target(game: &GameState, slot: usize) -> Option<[i32; 3]> {
    let entity = &game.entities[slot];
    if entity.look_at_flags & 0x80 == 0 {
        return None;
    }
    let target = game.entities.get(usize::from(entity.target_entity?))?;
    Some([
        target.pos[0],
        target.pos[1] - LOOK_AT_HEAD_HEIGHT,
        target.pos[2],
    ])
}

#[cfg(test)]
mod tests {
    use super::*;

    fn model_with_damage(clips: usize) -> Emd {
        Emd {
            skeleton: crate::model::Skeleton::default(),
            keyframes: vec![Keyframe::default()],
            clips: Vec::new(),
            damage_clips: vec![Clip::default(); clips],
            mesh: crate::model::Tmd::default(),
            texture: crate::model::Texture8 {
                width: 0,
                height: 0,
                indices: Vec::new(),
                palettes: Vec::new(),
                stp: Vec::new(),
            },
        }
    }

    /// The damage-scratch store: a model with a second bank repoints the
    /// player pair; one without leaves the last bank in place.
    #[test]
    fn a_model_with_a_damage_bank_repoints_the_player_pair() {
        let mut game = GameState::default();
        let keyframes = Arc::new(vec![Keyframe::default()]);
        note_player_damage_bank(
            &mut game,
            Some(&model_with_damage(2)),
            Some(Arc::clone(&keyframes)),
        );
        let bank = game.player_damage.as_ref().expect("the bank is set");
        assert_eq!(bank.clips.len(), 2);
        assert!(Arc::ptr_eq(&bank.keyframes, &keyframes));

        let plain = model_with_damage(0);
        note_player_damage_bank(&mut game, Some(&plain), Some(keyframes));
        assert_eq!(
            game.player_damage.as_ref().unwrap().clips.len(),
            2,
            "a model without a second bank leaves the pair untouched"
        );
    }

    #[test]
    fn live_look_at_target_follows_the_named_entity() {
        let mut game = GameState::default();
        game.entities[1].look_at_flags = 0x80;
        game.entities[1].target_entity = Some(3);
        game.entities[3].pos = [100, 50, -20];
        assert_eq!(live_look_at_target(&game, 1), Some([100, 50 - 0xA28, -20]));

        game.entities[1].look_at_flags = 0;
        assert_eq!(live_look_at_target(&game, 1), None);

        game.entities[1].look_at_flags = 0x80;
        game.entities[1].target_entity = Some(0xFE);
        assert_eq!(live_look_at_target(&game, 1), None);
    }

    #[test]
    fn camera_zone_test_uses_the_current_camera_header() {
        use crate::state::Zone;
        let room = RoomState {
            zones: vec![Zone {
                cam_from: 1,
                cam_to: 0,
                corners: [[0, 0], [0, 100], [100, 100], [100, 0]],
            }],
            ..RoomState::default()
        };
        assert!(in_camera_zone(&room, 1, [50, 0, 50]));
        assert!(!in_camera_zone(&room, 1, [150, 0, 50]));
        assert!(!in_camera_zone(&room, 0, [50, 0, 50]));
    }
}
